apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-project
  namespace: argocd
spec:
  description: Demo project for GitOps FastAPI
  sourceRepos:
    - 'https://github.com/YOUR_ORG/app-config'
  destinations:
    - namespace: dev
      server: 'https://kubernetes.default.svc'
    - namespace: prod
      server: 'https://kubernetes.default.svc'
